# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'kangfuba' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kangfuba
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'SnapKit', '~> 3.0.2'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'ObjectMapper', '~> 2.1'
  pod 'MJRefresh'
  pod 'AFNetworking', '~> 3.0'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'Gifu', '~> 2.0.0-rc'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'UMengAnalytics'
  target 'kangfubaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kangfubaUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
